<?php


namespace App\GraphQL;


use App\Models\Grade;
use App\Models\Video;
use App\Shared\GraphqlResolver;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

/**
 * Class VideoResolver
 * @property Video $model
 * @package App\GraphQL
 */
class VideoResolver extends GraphqlResolver
{

  protected function transformArguments(array $arguments)
  {
    $arguments['description'] = json_encode($arguments['description']);
    return parent::transformArguments($arguments); // TODO: Change the autogenerated stub
  }

  public function getExcluded(array $array): array
  {
    return ["content"];
  }

  public function makeModel(): Model
  {
    if (isset($this->modelArguments['id'])){
      $id = $this->modelArguments['id'];
      unset($this->modelArguments['id']);
      return Video::find($id);
    }
    return Video::create($this->modelArguments);
  }

  protected function afterCreate()
  {
    $this->customModelUpdate(
      [["content", "attachContent"]]
    );
  }

  protected function afterUpdate()
  {
    $this->customModelUpdate(
      [["content", "attachContent"]]
    );
  }

  public function search($builder, string $value){
    if (! $value) return $builder;
    $gradeIds = Grade::where("name", "like", $value)->select("id")->get()->pluck("id");
    $videoIds = Video::where("title", "like", $value)->select("id")->get()->pluck("id");
    return $builder->whereIn("id", $videoIds)->orWhereIn("grade_id", $gradeIds);
  }

  public function getByGrade($builder, string $gradeId){
    return Video::whereGradeId($gradeId);
  }

}
