<?php


namespace App\GraphQL;


use App\Models\Video;
use App\Shared\GraphqlResolver;
use Illuminate\Database\Eloquent\Model;

/**
 * Class VideoResolver
 * @property Video $model
 * @package App\GraphQL
 */
class VideoResolver extends GraphqlResolver
{

  protected function transformArguments(array $arguments)
  {
    $arguments['description'] = json_encode($arguments['description']);
    return parent::transformArguments($arguments); // TODO: Change the autogenerated stub
  }

  public function getExcluded(array $array): array
  {
    return ["content"];
  }
  public function makeModel(): Model
  {
    if (isset($this->modelArguments['id'])){
      $id = $this->modelArguments['id'];
      unset($this->modelArguments['id']);
      return Video::find($id);
    }
    return Video::create($this->modelArguments);
  }
  protected function afterCreate()
  {
    $this->customModelUpdate(
      [["content", "attachContent"]]
    );
  }
  protected function afterUpdate()
  {
    $this->customModelUpdate(
      [["content", "attachContent"]]
    );
  }
}
